services:
    fake_queue:
        class: FrontBundle\Infraestructure\FakeQueue

    fake_queue_document_handler:
        class: FrontBundle\Infraestructure\FakeQueueDocumentsHandler
        arguments:
            - "@fake_queue"

    amazon_sqs_document_handler:
        class: FrontBundle\Infraestructure\AmazonSqsQueueDocumentsHandler
        arguments:
            - "@aws.sqs"
            -  "https://sqs.eu-west-1.amazonaws.com/486488213723/mpwar_tfm"

    es_repository:
        class: FrontBundle\Infraestructure\ESDocumentRepository
        arguments:
            - "@fos_elastica.index.tfm_document"

    document_saver:
        class: FrontBundle\Application\DocumentSaver
        arguments:
            - "@amazon_sqs_document_handler"
            - "@es_repository"

    documents_by_date_use_case:
            class: FrontBundle\Application\UseCase\GetDocumentsByDate
            arguments:
                - "@es_repository"

    documents_by_category_use_case:
                class: FrontBundle\Application\UseCase\GetDocumentsByCategory
                arguments:
                    - "@es_repository"

    documents_by_location_use_case:
                    class: FrontBundle\Application\UseCase\GetDocumentsByLocation
                    arguments:
                        - "@es_repository"

    total_documents_use_case:
                class: FrontBundle\Application\UseCase\GetTotalDocuments
                arguments:
                    - "@es_repository"

    average_sentiment_use_case:
                    class: FrontBundle\Application\UseCase\GetAverageSentiment
                    arguments:
                        - "@es_repository"




