services:
    fake_queue:
        class: FrontBundle\Infraestructure\FakeQueue

    fake_queue_document_handler:
        class: FrontBundle\Infraestructure\FakeQueueDocumentsHandler
        arguments:
            - "@fake_queue"

    es_repository:
        class: FrontBundle\Infraestructure\ESDocumentRepository
        arguments:
            - "@fos_elastica.index.documents"

    document_saver:
        class: FrontBundle\Application\DocumentSaver
        arguments:
            - "@fake_queue_document_handler"
            - "@es_repository"

    index_information_use_case:
        class: FrontBundle\Application\IndexInformationUseCase
        arguments:
            - "@es_repository"


