ansistrano_deploy_from: "{{ playbook_dir }}/.." # Where my local project is (relative or absolute path)
ansistrano_deploy_to: "/var/www/tfm-front-end" # Base path to deploy to.
ansistrano_version_dir: "releases" # Releases folder name
ansistrano_current_dir: "current" # Softlink name. You should rarely changed it.
ansistrano_current_via: "symlink" # Deployment strategy who code should be deployed to current path. Options are symlink or rsync
ansistrano_keep_releases: 3 # Releases to keep after a new deployment. See "Pruning old releases".

ansistrano_deploy_via: "rsync" # Method used to deliver the code to the server. Options are copy, rsync, git, svn, s3 or download. Copy, download and s3 have an optional step to unarchive the downloaded file which can be used by adding _unarchive. You can check all the options inside tasks/update-code folder!
ansistrano_allow_anonymous_stats: no

# Variables used in the rsync deployment strategy
ansistrano_rsync_extra_params: "--exclude-from={{ playbook_dir }}/files/exclude_list.txt" # Extra parameters to use when deploying with rsync in a single string. Although Ansible allows an array this can cause problems if we try to add multiple --include args as it was reported in https://github.com/ansistrano/deploy/commit/e98942dc969d4e620313f00f003a7ea2eab67e86
ansistrano_rsync_set_remote_user: yes # See [ansible synchronize module](http://docs.ansible.com/ansible/synchronize_module.html). Options are yes, no.

#ansistrano_after_symlink_tasks_file: "../../deploy_hooks/tasks/my-after-symlink-tasks.yml"